repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --check
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --all-targets -- --deny warnings
        language: system
        types: [rust]
        pass_filenames: false

      - id: taplo-fmt
        name: taplo fmt
        entry: taplo fmt --check
        language: system
        types: [toml]


      - id: cargo-deny
        name: cargo deny check licenses
        entry: cargo deny check licenses
        language: system
        pass_filenames: false
        always_run: true
