name: CI

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  nix:
    name: test with Nix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Run flake check
        run: nix flake check -L --show-trace

  cargo:
    name: test with Cargo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        # dig is needed for integration tests
        run: sudo apt-get update && sudo apt-get install -y dnsutils pre-commit

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy

      - name: Install cargo-audit
        run: cargo install cargo-audit --locked

      - name: Install cargo-deny
        run: cargo install cargo-deny --locked

      - name: Install taplo
        run: cargo install taplo-cli --locked

      - name: Check formatting
        run: cargo fmt --check

      - name: Check TOML formatting
        run: taplo fmt --check

      - name: Run clippy
        run: cargo clippy --all-targets -- --deny warnings

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Audit dependencies
        run: cargo audit

      - name: Check licenses
        run: cargo deny check licenses

      - name: Run pre-commit hooks
        run: pre-commit run --all-files
